name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Or 'master', depending on your default branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload static files
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'  # Deploy everything in the repo root

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
